gg:
  jte:
    development-mode: true

spring:
  application:
    name: quiz
  security:
    user:
      name: admin
      password: 123456

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    url: jdbc:postgresql://192.168.1.101:5433/quizdb
    username: quizuser
    password: quizpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate  # ✅ Liquibase istifadə edərkən Hibernate avtomatik cədvəl yaratmamalıdır
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml  # ✅ əsas changelog faylı

server:
  port: 8081

