gg:
  jte:
    development-mode: true

spring:
  application:
    name: quiz

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    url: jdbc:postgresql://localhost:5433/quizdb
    username: quizuser
    password: quizpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

